# Configuration for:
#   (a) Processing of ROOT trees into histograms
#   (b) Analysis of histograms into final result
#
# The observables are structured into observable blocks (e.g. theta_g, subjet_z, etc.)
# each containing multiple individual subconfigurations (e.g. zcut, beta, subjetR, etc.),
# where each subconfiguration corresponds to a single unfolded result.
# One can also specify a list of jetR, which will be looped over.
#
# The process step is intended to loop over all observables simultaneously
# The analysis step is intended to run for a single observable block

process_observables: ['inclusive_subjet_z', 'leading_subjet_z']
jetR: [0.4]
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0.0
eta_max: 0.9
debug_level: 0
dry_run: False
fast_simulation: False

# Observable block
inclusive_subjet_z:

  common_settings:
    xtitle: '#it{z_{r}}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{z_{r}}}'
    pt_bins_reported: [80, 120]
    max_reg_param: 10
    plot_overlay_list:
      - ['config1', 'config2']
      
  # RM binnings from processing:
  #   pt-truth: 10 GeV
  #   pt-det: 5 GeV
  #   z-truth: 0.01
  #   z-det: 0.01

  config1:
    subjet_R: 0.1
    pt_bins_truth: [5, 20, 40, 60, 80, 120, 150, 200]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120, 150]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    obs_bins_truth: [0., 0.02, 0.04, 0.1, 0.3, 0.6, 0.7, 0.77, 0.83, 0.89, 0.95, 1.0]
    obs_bins_det: [0., 0.02, 0.04, 0.1, 0.3, 0.6, 0.7, 0.77, 0.83, 0.89, 0.95, 1.0]
    obs_bins_det_sys_binning: [0., 0.01, 0.02, 0.03, 0.04, 0.06, 0.12, 0.18, 0.24, 0.3, 0.36, 0.42, 0.48, 0.54, 0.6, 0.66, 0.72, 0.8, 0.9, 0.96, 0.98, 0.99, 1.0]

  config2:
    subjet_R: 0.2
    pt_bins_truth: [5, 20, 40, 60, 80, 120, 150, 200]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120, 150]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    obs_bins_truth: [0., 0.02, 0.04, 0.1, 0.3, 0.7, 0.8, 0.86, 0.9, 0.94, 0.98, 1.0]
    obs_bins_det: [0., 0.02, 0.04, 0.1, 0.3, 0.7, 0.8, 0.86, 0.9, 0.94, 0.98, 1.0]
    obs_bins_det_sys_binning: [0., 0.01, 0.02, 0.03, 0.04, 0.06, 0.12, 0.18, 0.24, 0.3, 0.36, 0.42, 0.48, 0.54, 0.6, 0.66, 0.72, 0.8, 0.9, 0.96, 0.98, 0.99, 1.0]

# Observable block
leading_subjet_z:

  common_settings:
    xtitle: '#it{z_{r}}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{z_{r}}}'
    pt_bins_reported: [80, 120]
    max_reg_param: 10
    plot_overlay_list:
      - ['config1', 'config2']
      
  # RM binnings from processing:
  #   pt-truth: 10 GeV
  #   pt-det: 5 GeV
  #   z-truth: 0.01
  #   z-det: 0.01

  config1:
    subjet_R: 0.1
    pt_bins_truth: [5, 20, 40, 60, 80, 120, 150, 200]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120, 150]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    obs_bins_truth: [0., 0.6, 0.7, 0.77, 0.83, 0.89, 0.95, 1.0]
    obs_bins_det: [0., 0.6, 0.7, 0.77, 0.83, 0.89, 0.95, 1.0]
    obs_bins_det_sys_binning: [0., 0.5, 0.6, 0.7, 0.8, 0.9, 0.93, 0.95, 0.96, 0.97, 0.98, 0.99, 1.0]
    
  config2:
    subjet_R: 0.2
    pt_bins_truth: [5, 20, 40, 60, 80, 120, 150, 200]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120, 150]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    obs_bins_truth: [0., 0.7, 0.8, 0.86, 0.9, 0.94, 0.98, 1.0]
    obs_bins_det: [0., 0.7, 0.8, 0.86, 0.9, 0.94, 0.98, 1.0]
    obs_bins_det_sys_binning: [0., 0.5, 0.6, 0.7, 0.8, 0.9, 0.93, 0.95, 0.96, 0.97, 0.98, 0.99, 1.0]

###############################################################################
# Theory folding parameters

# Generating RM
response_levels: [['h','ch','off']]
th_subconfigs: ['config1','config2']
theory_pt_bins: [50,60,70,80,90,100,110,120,130,140,160,180,200]

# Folding theory
th_fold_observable: 'leading_subjet_z'
theory_dir: '/home/james/pyjetty/pyjetty/alice_analysis/analysis/user/james/subjet_z'
pt_scale_factors_path: '/home/james/pyjetty/pyjetty/alice_analysis/analysis/user/james/subjet_z'
response_files: ["/rstorage/alice/AnalysisResults/james/934921/AnalysisResultsFinal.root","/rstorage/alice/AnalysisResults/james/934865/AnalysisResultsFinal.root"]
response_labels: ["PYTHIA8","Herwig7"] 
final_pt_bins: [80, 120]

#There are a few options available for which binning the user wants for the observable to have. 
# If no options are specified, I think the default is to bin with the binning used in the data analysis
#theory_obs_bins: [0.,0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.16,0.17,0.18,0.19,0.2]
#use_nominal_ana_binning: True

###############################################################################
# Analysis parameters

file_format: '.pdf'
output_dir: '/Users/jamesmulligan/Analysis_subjet_z/output_analysis/pp/493677-04-paper'
roounfold_path: '/Users/jamesmulligan/heppy/external/roounfold/roounfold-current/lib/libRooUnfold.dylib'

analysis_observable: 'leading_subjet_z'
do_unfolding: False
force_rebin: True
do_systematics: True
do_plot_final_result: True
do_plot_performance: False
figure_approval_status: ''

# List of which systematics to perform
systematics_list:
  - main
  - trkeff
  - prior1
  - prior2
  - truncation
  - binning
  - fastsim_generator0
  - fastsim_generator1
#  - delta_matching      # Note: only include for inclusive case

# Paths to processing output, to be used for unfolding
main_data: '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC17pq/493677/AnalysisResultsFinal.root'
main_response: '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC18b8/493678/AnalysisResultsFinal.root'
trkeff_response: '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC18b8_trkeff/493679/AnalysisResultsFinal.root'
delta_matching_response: '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC18b8_matching/821755/AnalysisResultsFinal.root'
fastsim_response:
 - '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC18b8_fastsim_pythia/493680/AnalysisResultsFinal.root'
 - '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC18b8_fastsim_herwig/493681/AnalysisResultsFinal.root'

# Prior variation parameters
#prior_variation_option: 4              # Leading subjets
prior_variation_option: 1             # Inclusive subjets
prior1_variation_parameter: 0.5
prior2_variation_parameter: -0.5
